# CLEAR PALABRAS RESERVADAS

def CLEAR_LIST_RESERVADAS (LIMPIADOR):
    i = 0
    LIST_CLEAR = []

    while i <= (len(LIMPIADOR) - 1):
        CLEAR = LIMPIADOR[i].rstrip('\n') 
        LIST_CLEAR.append(CLEAR)
        i = i + 1

    return LIST_CLEAR  # RETORNA A LA FUNCION ALASIS LEXICO LA LISTA DE PALABRAS RESERVADAS SIN EL \n 

#FUNCION ANALISIS LEXICO
def ANALISIS_LIXICO(LIST , PALABRAS):
    LIST_IN_LEXICO = LIST
    LIST_DEPURADA = []
    LIST_TOKEN = []
    MENSAJERO_PALABRAS_RESERVADAS = CLEAR_LIST_RESERVADAS(PALABRAS)
    PALABRAS_RESERVADAS_LIMPIA = MENSAJERO_PALABRAS_RESERVADAS
    
    #PRIMERA FASE PARA DEPURAR COMENTARIOS Y ESPACIOS
    
    #CICLO PARA DEPURAR COMENTARIOS Y ESPACIOS EN BLANCO
    CONTADOR_DEPURADOR = 0
    while CONTADOR_DEPURADOR <= (len(LIST_IN_LEXICO)-1): # CICLO PARA ELIMINAR ESPACIOS Y COMENTARIOS

        #CONDICIONES DE UN COMMIT Y UN SPACE

        if LIST_IN_LEXICO[CONTADOR_DEPURADOR][0] == "#" :
            pass
        elif LIST_IN_LEXICO[CONTADOR_DEPURADOR] == "\n":
            pass
          
        else:
            LINEA_DEPURADA = LIST_IN_LEXICO[CONTADOR_DEPURADOR].rstrip('\n') #ELIMINAMOS LOS SALTOS DE LINEA AL FINAL DE UNA CADENA
            LIST_DEPURADA.append(LINEA_DEPURADA) #PROCESO PARA LLENAR LA LISTA LIMPIA

        CONTADOR_DEPURADOR = CONTADOR_DEPURADOR + 1

    #SEGUNDA FASE SEPARAR CARACTERES
    
    LISTA_CARACTERS = [] #LISTA PARA LOS CARACTERES 
    CONTADOR_CHAR_1 = 0
    CONTADOR_CHAR_2 = 0

    while CONTADOR_CHAR_1 <= (len(LIST_DEPURADA)-1):
        while  CONTADOR_CHAR_2 <= (len(LIST_DEPURADA[CONTADOR_CHAR_1])-1): #CONTADOR PARA ELIMINAR ESPACIOS Y ALMACENAR CARACTERES
            if LIST_DEPURADA[CONTADOR_CHAR_1][CONTADOR_CHAR_2] != " ":
                LISTA_CARACTERS.append(LIST_DEPURADA[CONTADOR_CHAR_1][CONTADOR_CHAR_2]) # LISTA CON SOLO CARACTERES
            else:
                pass 
            CONTADOR_CHAR_2 = CONTADOR_CHAR_2 + 1   
        
        CONTADOR_CHAR_2 = 0        
        CONTADOR_CHAR_1 = CONTADOR_CHAR_1 + 1

    return LISTA_CARACTERS


#ANALIZADOR DEL CODIGO FUENTE

#VARIABLES CODIGO
BOOK_CODE = open ("Contenedor_code.txt" , "r") # ABRIMOS EL CODIGO
LIST_BOOK_CODE = BOOK_CODE.readlines() # GUARDAMOS LAS LINEAN EN UN VECTOR
BOOK_PALABRAS_RESERVADAS = open("Palabras_Reservadas.txt" , "r") # ARCHIVO PALABRAS RESERVADAS
LIST_RESERVADAS = BOOK_PALABRAS_RESERVADAS.readlines() #VECTOR PALABRAS RESERVADAS
TO_GO_LEXICO = ANALISIS_LIXICO(LIST_BOOK_CODE , LIST_RESERVADAS) # ENVIAMOS EL VECTOR A ANALISIS LEXICO
print(TO_GO_LEXICO)
BOOK_CODE.close()
BOOK_PALABRAS_RESERVADAS.close()